### ISSUE TITLE
UI API called from background thread - iOS 14 Crash

### ISSUE THREAD

**Issue by idanb-giniapps** [brightcove/brightcove-player-sdk-ios-ima#7]
Hello,

We have been getting a crash when the video player is closed during ad playback. 

![Xcode Screenshot](https://user-images.githubusercontent.com/59220837/104578362-4c7ddc80-5663-11eb-905a-c682b0df5581.png)

Here is the [stack trace](https://pastebin.com/raw/6ZCqgmng)

## More Info
Brightcove IMA SDK Version: 6.8.3
Brightcove Core SDK Version: 6.8.3 (managed by CocoaPods)
GoogleAds-IMA-iOS-SDK Version: 3.12.1 (managed by CocoaPods)
iOS 14

Please advise.

**Comment by timothyrodgers** [comment]
Brightcove does not provide technical support through GitHub. If you need support or want to provide feedback, please use the support portal (https://supportportal.brightcove.com/) or contact your Account Manager. We value all your feedback.

Your issue appears to be caused by the IMA framework. When contacting Brightcove support, please provide clear steps to reproduce the crash and if possible, provide a working sample project which reproduces the behavior.
